services:
  rest_api:
    container_name: rest_api
    restart: on-failure
    build: ./
    ports:
      - "8080:8080"
  mongo:
    container_name: mongo_rest_api
    image: mongo
    ports:
      - "27017:27017"
