name: Discord_clone Integration

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run ci
      - run: yarn run lint
      - run: yarn run build
