version: '2.1'
orbs:
  github-super-linter: circleci/github-super-linter@1.0
workflows:
  lint-code:
    jobs:
      - github-super-linter/lint:
          context: Super-Linter-Options
          version: v3.17.0
